server:
  port: 8081
  servlet:
    context-path: /user # 项目的前缀

spring:
  datasource: # Mybatis 数据库连接配置
    driver-class-name: com.mysql.jdbc.Driver  # driver-class-name：5.7版本为 com.mysql.jdbc.Driver；8.0版本为 com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test_user?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印完整带参数SQL语句
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  mapper-locations: classpath:/mapper/**.xml

logging:
  level:
    garry:
      train:
        member:
          mapper: trace # garry.train.member.mapper下的日志等级设置为 trace，可以打印出 sql

test:
  me: 看见我就说明没有使用 Nacos
